version: '2'

services:
  metabase:
    container_name: metabase-container
    image: metabase/metabase
    ports:
      - 3000:3000
    links:
      - db
  db:
    container_name: metabase-db-container
    image: mysql:5.7
    volumes:
        - ./mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app