version: '2'

services:
  superset:
    container_name: superset-container
    image: amancevice/superset
    ports:
      - 8088:8088
    links:
      - superset-druid
    volumes:
      - ./superset-data:/etc/superset
  superset-druid:
    container_name: superset-druid-container
    image: druidio/example-cluster
    ports:
      - "8082:8082"
      - "8081:8081"
    volumes:
      - ./superset-data:/etc/superset
  # user banco pronto
  # superset-db:
  #   container_name: superset-db-container
  #   image: mysql:5.7
  #   volumes:
  #       - ./mysql-data:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_USER: app
  #     MYSQL_PASSWORD: app
  #     MYSQL_DATABASE: app