version: '2'

services:
  metabase:
    container_name: superset-container
    image: amancevice/superset
    ports:
      - 8088:8088
    links:
      - db
  db:
    container_name: superset-db-container
    image: mysql:5.7
    volumes:
        - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app